### PR TITLE
Update MercadoBitcoin's api to version 3.

### PR DESCRIPTION
**Pull request by pdroalves**
This commit adds support to version 3 of MercadoBitcoin's api, one of the exchange rates.

### CODE REVIEW

**Comment by pooler** [comment]
Shouldn't `history_ccys` only be defined if historical rates are available?

**Comment by pdroalves** [comment]
Don't know. But without `history_ccys` I can't see "MercadoBitcoin" in source list.

**Comment by pooler** [comment]
That is expected if you checked "Show history rates". Try unchecking it.

**Comment by pdroalves** [comment]
You are completely right. I fixed it.

**Pull request merged**
