### PR TITLE
Fixed firmware requirement for segwit on Ledger

### PR DESCRIPTION
**Pull request by wolfmankurd**
Was hardcoded with bitcoin firmware (1.1.10) Ledger supports segwit as of 1.1.9 (latest version).

### CODE REVIEW

**Comment by wolfmankurd** [comment]
Can't test sending since I can't sync with segwit (on or off ledger) but generates correct addresses (compared to official Ledger wallet).

**Comment by pooler** [comment]
This is specific to the "Litecoin" app on Ledger, correct?

Do you know if there's a changelog somewhere documenting this?

**Comment by wolfmankurd** [comment]
Unforuntately it can't find the ledger app for litecoin on their github and so no change log.

The chrome app added support to segwit in [1.9.0](https://github.com/LedgerHQ/ledger-wallet-chrome/blob/master/CHANGELOG.md) which was released on [27th August 2017](https://github.com/LedgerHQ/ledger-wallet-chrome/releases?after=1.9.1).

So if we knew what the version of the Ledger Litecoin App was at that time we might find an earlier version which also (before 1.1.9) supported segwit.

**Comment by mautematico** [comment]
This change WFM on latest electrum-ltc and latest ledger nano s' litecoin app.
Please merge and release 👍

**Pull request merged**
